alert("JavaScript - External Script file!!!")
alert("JavaScript - External Script file!!!")
alert("JavaScript - External Script file!!!")
alert("JavaScript - External Script file!!!")
alert("JavaScript - External Script file!!!")